"""Phase 14 UC5 and UC8 -- decisions scored from REGENERATED simulation paths.

Phase 12 B2 never stored its Monte Carlo paths (aggregates only). They are regenerated here with the EXACT code that
produced the stored figures -- ml/opt/order_policy.py as of commit 9e2d59d, loaded from git, because Phase 12 B3's
part-grouped blocks changed the random stream -- and the same seeds (rng = default_rng(11) per fill seed, snapshots in
order). IDENTITY GATE: every regenerated 2025 snapshot's below-SS fraction must equal the stored B2 value exactly, or
the script stops. Validation (2024) snapshots are generated by the same code (no stored reference exists for them).

UC5  "this part-plant-week will be below safety stock": P_sim(level < SS) >= theta, against
       (a) the OBSERVED store (on hand < SS) and (b) PRIVILEGED__prerescue_below_ss (on hand - net transfer < SS),
     matched per part-plant-week (store week_start = t0 + 7(w + 1)). theta fitted on VALIDATION, max F1, separately
     for (a) and (b). Sweep theta 0.1..0.9 against (a), (b) and "planners acted" (a transfer-in recorded that week).
UC8  the S2 rules at S2's theta sweep: RECIPIENT confusion over every projected-short part-plant-week; DONOR confusion
     over every (projected-short part-plant-week, same-part candidate) pair. Donor truth is INFERRED (deviation 119).
inventory_position_weekly: read by montecarlo.opening_position / order_policy (as-of t0, sanctioned simulation path)
and by the reference builder here (2024-2026 weeks, evaluation only).
"""
from __future__ import annotations
import os, sys, json, subprocess, importlib.util, time
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:0] = [HERE, os.path.join(HERE, ".."), os.path.join(HERE, "..", "eval"), os.path.join(HERE, "..", "opt"),
                os.path.join(HERE, "..", "data")]
import numpy as np, pandas as pd
import phase12_common as C
import montecarlo as MC
from phase14_score import fit_tau, decide
import phase13_s2 as S2

B2_COMMIT = "9e2d59d"
D = C.REPO + "/db/gen_v8/seed_1001"
W, N = MC.HORIZON_WEEKS, 200
SEEDS = C.V8_SEEDS
S2_THETAS = (0.02, 0.05, 0.10, 0.20, 0.30, 0.50)


def b2_order_policy():
    src = subprocess.check_output(["git", "-C", C.REPO, "show", f"{B2_COMMIT}:ml/opt/order_policy.py"], text=True)
    path = os.path.join(C.ART, "cache", f"order_policy_{B2_COMMIT}.py")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write(src)
    spec = importlib.util.spec_from_file_location("order_policy_b2", path)
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
    return m


def snapshots(lo, hi):
    s = pd.read_csv(f"{D}/snapshots.csv", usecols=["as_of_ts"]).as_of_ts
    return sorted(pd.Timestamp(x) for x in s if pd.Timestamp(lo) <= pd.Timestamp(x) <= pd.Timestamp(hi))


def store_labels():
    tx = pd.read_csv(f"{D}/inventory_transactions.csv", usecols=["part_id", "plant_id", "txn_type", "qty", "event_ts"])
    tx = tx[tx.txn_type.isin(["transfer_in", "transfer_out"])]
    tx["week"] = pd.to_datetime(tx.event_ts).dt.to_period("W-SUN").dt.start_time
    g = tx.groupby(["part_id", "plant_id", "week", "txn_type"]).qty.sum().unstack(fill_value=0)
    pw = pd.read_csv(f"{D}/inventory_position_weekly.csv",
                     usecols=["part_id", "plant_id", "week_start", "qty_on_hand", "safety_stock_qty"])
    pw["week"] = pd.to_datetime(pw.week_start)
    pw = pw[pw.week >= "2024-01-01"].join(g, on=["part_id", "plant_id", "week"]).fillna({"transfer_in": 0, "transfer_out": 0})
    pw["net"] = pw.transfer_in + pw.transfer_out
    pw["obs_below"] = pw.qty_on_hand < pw.safety_stock_qty
    pw["pre_below"] = (pw.qty_on_hand - pw.net) < pw.safety_stock_qty
    pw["acted"] = pw.transfer_in > 0
    return pw.set_index(["part_id", "plant_id", "week"])[["obs_below", "pre_below", "acted"]]


def main():
    st = C.require_clean()
    OPb = b2_order_policy()
    pp, _, _ = MC.part_plant_universe("v8")
    sub = pp.reset_index(drop=True)
    stored = json.load(open(os.path.join(C.ART, "phase12_b2_validate.json")))
    stored_s = json.load(open(os.path.join(C.ART, "phase12_b2_seeds.json")))
    stored_ps = {7: {p["snapshot"]: p["below_ss"] for p in stored["policy_rop"]["per_snapshot"]}}
    for s in (17, 27, 37, 47):
        stored_ps[s] = {p["snapshot"]: p["below_ss"] for p in stored_s[f"policy_rop_fill_s{s}"]["per_snapshot"]}
    labels = store_labels()
    truth = S2.Truth()
    pl = pd.read_csv(f"{D}/plants.csv", usecols=["plant_id", "latitude", "longitude"])
    plants_ll = {r.plant_id: (r.latitude, r.longitude) for r in pl.itertuples()}
    parts, plant = sub.part_id.to_numpy(), sub.plant_id.to_numpy()
    by_part = pd.Series(np.arange(len(sub))).groupby(parts).apply(list).to_dict()
    R = dict(stamp=st, b2_commit=B2_COMMIT, paths=N, gate=[], uc5={}, uc8={})
    rows = {}           # (fold, seed) -> dict of arrays: p_short, obs, pre, acted
    uc8 = {}            # (fold, seed, theta, rule) -> counts
    for fold, (lo, hi) in (("test", ("2025-01-01", "2025-12-31")), ("val", ("2024-01-01", "2024-12-31"))):
        for seed in SEEDS:
            rng = np.random.default_rng(11)
            draw = OPb.make_draw("rop", fill_seed=seed)
            acc = dict(p=[], obs=[], pre=[], acted=[], missing=0)
            for t0 in snapshots(lo, hi):
                t = time.time()
                op = MC.opening_position("v8", t0, sub)
                arr, cons, _ = draw("v8", t0, sub, W, N, rng, op)
                I0 = op.qty_on_hand.fillna(0).to_numpy(float); ss = op.safety_stock_qty.fillna(1).to_numpy(float)
                pos, _ = MC.roll_forward(I0, arr, cons, ss)
                frac = float((pos < ss[:, None, None]).mean())
                if fold == "test":
                    ref = stored_ps[seed][str(t0.date())]
                    ok = frac == ref
                    R["gate"].append(dict(seed=seed, t0=str(t0.date()), regenerated=frac, stored=ref, exact=ok))
                    assert ok, f"IDENTITY GATE: seed {seed} {t0.date()} regenerated {frac} != stored {ref}"
                p_short = (pos < ss[:, None, None]).mean(2)                          # [P, W]
                weeks = [t0 + pd.Timedelta(days=7 * (w + 1)) for w in range(W)]
                weeks = [w - pd.Timedelta(days=w.weekday()) for w in weeks]
                idx = pd.MultiIndex.from_arrays([np.repeat(parts, W), np.repeat(plant, W), np.tile(weeks, len(sub))])
                lab = labels.reindex(idx)
                ok = lab.obs_below.notna().to_numpy()
                acc["missing"] += int((~ok).sum())
                acc["p"].append(p_short.reshape(-1)[ok]); acc["obs"].append(lab.obs_below.to_numpy()[ok].astype(bool))
                acc["pre"].append(lab.pre_below.to_numpy()[ok].astype(bool)); acc["acted"].append(lab.acted.to_numpy()[ok].astype(bool))
                # UC8: S2's rules on the same paths (ss as S2 used it: SS filled with 0)
                ss0 = op.safety_stock_qty.fillna(0).to_numpy(float)
                pos0 = pos  # levels are the same; only the SS used for "short" differs for orphan rows with missing SS
                for th in S2_THETAS:
                    pol, nai, rnd = S2.recommend(t0, sub, pos0, ss0, I0, plants_ll, th,
                                                 rng=np.random.default_rng(pd.Timestamp(t0).toordinal() * 100 + seed))
                    short = np.argwhere((pos0 < ss0[:, None, None]).mean(2) >= S2.SHORT_P)
                    for rule, recs in (("policy", pol), ("naive", nai), ("random", rnd)):
                        k = (fold, seed, th, rule)
                        c = uc8.setdefault(k, dict(rTP=0, rFP=0, rFN=0, rTN=0, dTP=0, dFP=0, dFN=0, dTN=0))
                        chosen = {(r["r"], r["w"]): r["d"] for r in recs}
                        for i, w in short:
                            wk = weeks[w]
                            acted = (parts[i], plant[i], wk) in truth.tin
                            rec = (i, int(w)) in chosen
                            c["rTP"] += rec and acted; c["rFP"] += rec and not acted
                            c["rFN"] += (not rec) and acted; c["rTN"] += (not rec) and not acted
                            for j in by_part[parts[i]]:
                                if j == i:
                                    continue
                                donor_true = acted and (parts[i], plant[j], wk) in truth.tout
                                picked = chosen.get((i, int(w))) == j
                                c["dTP"] += picked and donor_true; c["dFP"] += picked and not donor_true
                                c["dFN"] += (not picked) and donor_true; c["dTN"] += (not picked) and not donor_true
                del pos, pos0, arr, cons
                print(f"   {fold} seed {seed} {t0.date()} below {frac:.5f} ({time.time() - t:.0f}s)", flush=True)
            rows[(fold, seed)] = {k: (np.concatenate(v) if isinstance(v, list) else v) for k, v in acc.items()}
    # ---------------- UC5: thresholds on VALIDATION, per reference, per seed; then TEST
    for ref in ("obs", "pre"):
        name = "a_observed" if ref == "obs" else "b_PRIVILEGED__prerescue_below_ss"
        per, sweep = [], {}
        for seed in SEEDS:
            v, t = rows[("val", seed)], rows[("test", seed)]
            tau, vobj = fit_tau(v["p"], v[ref].astype(int), "f1")
            m = decide(t["p"], t[ref].astype(int), tau); m["tau"] = tau; m["seed"] = seed
            per.append(m)
            for th in np.round(np.arange(0.1, 0.91, 0.1), 1):
                for tgt in (ref, "acted"):
                    d = decide(t["p"], t[tgt].astype(int), th)
                    sweep.setdefault(f"{th}|{tgt}", []).append({k: d[k] for k in ("precision", "recall", "f1", "TP", "FP", "FN", "TN")})
        keys = ("tau", "n", "positives", "base_rate", "TP", "FP", "TN", "FN", "accuracy", "majority_accuracy",
                "accuracy_gain_over_majority", "precision", "recall", "f1", "majority_f1", "specificity", "mcc",
                "balanced_accuracy", "roc_auc", "pr_auc")
        R["uc5"][name] = dict(band={k: [float(np.nanmin([p[k] for p in per])), float(np.nanmean([p[k] for p in per])),
                                        float(np.nanmax([p[k] for p in per]))] for k in keys},
                              per_seed=per,
                              sweep={k: {m: [float(min(x[m] for x in v)), float(np.mean([x[m] for x in v])), float(max(x[m] for x in v))]
                                         for m in ("precision", "recall", "f1", "TP", "FP", "FN", "TN")} for k, v in sweep.items()})
    # the cells the planners' transfers moved, at each seed's (a) tau: rescued weeks (pre below, obs not)
    moved = []
    for i, seed in enumerate(SEEDS):
        t = rows[("test", seed)]; tau_a = R["uc5"]["a_observed"]["per_seed"][i]["tau"]
        rescued = t["pre"] & ~t["obs"]; pred = t["p"] >= tau_a
        moved.append(dict(seed=seed, rescued_weeks=int(rescued.sum()), rescued_and_sim_positive_FP_to_TP=int((rescued & pred).sum()),
                          rescued_and_sim_negative_TN_to_FN=int((rescued & ~pred).sum()),
                          pushed_below_by_transfer_out=int((t["obs"] & ~t["pre"]).sum()), missing_store_weeks=int(t["missing"])))
    R["uc5"]["cells_moved_by_transfers"] = moved
    # ---------------- UC8 confusion per theta, rule
    for (fold, seed, th, rule), c in uc8.items():
        if fold != "test":
            continue
        e = R["uc8"].setdefault(f"{th}|{rule}", [])
        for side in ("r", "d"):
            TP, FP, FN, TN = c[side + "TP"], c[side + "FP"], c[side + "FN"], c[side + "TN"]
            e.append(dict(seed=seed, side="recipient" if side == "r" else "donor_INFERRED_truth", TP=TP, FP=FP, FN=FN, TN=TN,
                          precision=TP / max(TP + FP, 1), recall=TP / max(TP + FN, 1), f1=2 * TP / max(2 * TP + FP + FN, 1),
                          specificity=TN / max(TN + FP, 1), accuracy=(TP + TN) / max(TP + FP + FN + TN, 1),
                          base_rate=(TP + FN) / max(TP + FP + FN + TN, 1)))
    print(json.dumps({k: v["band"] if isinstance(v, dict) and "band" in v else v for k, v in R["uc5"].items()}, indent=1, default=str)[:4000])
    print(C.dump(R, "phase14_sim.json"))


if __name__ == "__main__":
    main()
