#!/usr/bin/env python3
"""Regenerate a non-retained variant-seed on demand.

The spec-scale sweep is 12 variants x 5 seeds. At ~440 MB per variant-seed that is
~26 GB, well over the ~15 GB storage target, so `db/csv/` retains only the **two
lowest seeds (42 and 43)** of each variant and the other three (44, 45, 46) are
regenerated from this script when they are wanted. The trade is storage for compute
at a very favourable rate: ~7 min of CPU buys back ~440 MB, and the determinism
guarantee (same seed + same config -> byte-identical `.csv.gz`) makes the
regenerated copy exact rather than merely equivalent.

Why the two lowest: seed 42 is the generator's default and the seed the V1
byte-identity anchor is pinned to, and 43 is the next in `run_benchmark.py`'s
canonical `DEFAULT_SEEDS`. Any deterministic convention works; a stated one keeps
two people asking for "the retained seeds" from getting different answers.

Usage:
    python3 db/regenerate_seed.py --list
    python3 db/regenerate_seed.py --variant K --seed 44
    python3 db/regenerate_seed.py --all                    # every non-retained seed
    python3 db/regenerate_seed.py --verify --variant K --seed 42
"""
import argparse, filecmp, os, shutil, subprocess, sys, tempfile, time

HERE = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.join(HERE, "generate_dataset.py")
CSV = os.path.join(HERE, "csv")
ALL_VARIANTS = ["0", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K"]
ALL_SEEDS = [42, 43, 44, 45, 46]
RETAINED_SEEDS = [42, 43]          # on disk; the rest are regenerated by this script


def out_dir_for(variant, seed):
    return os.path.join(CSV, f"v{variant}_seed{seed}")


def du(path):
    return sum(os.path.getsize(os.path.join(dp, f))
               for dp, _dn, fn in os.walk(path) for f in fn)


def generate(variant, seed, config, out_dir):
    t0 = time.time()
    r = subprocess.run([sys.executable, GEN, "--variant", variant, "--seed", str(seed),
                        "--config", config, "--out-dir", out_dir],
                       capture_output=True, text=True)
    secs = time.time() - t0
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        sys.exit(f"generation failed: variant {variant} seed {seed}")
    fails = r.stdout.count("  [FAIL]")
    return secs, fails, r.stdout


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--variant", default="", help="variant to regenerate")
    ap.add_argument("--seed", type=int, default=0, help="seed to regenerate")
    ap.add_argument("--config", default="spec", help="preset name or JSON path")
    ap.add_argument("--out-dir", default="", help="default: db/csv/v<variant>_seed<seed>")
    ap.add_argument("--all", action="store_true",
                    help="regenerate every non-retained variant-seed (~36 runs)")
    ap.add_argument("--list", action="store_true",
                    help="show which variant-seeds are on disk and which are regenerable")
    ap.add_argument("--verify", action="store_true",
                    help="regenerate into a temp dir and diff the COMPRESSED bytes against "
                         "the on-disk copy -- the determinism check")
    args = ap.parse_args()

    if args.list:
        print(f"retained on disk: seeds {RETAINED_SEEDS}; regenerable: "
              f"{[s for s in ALL_SEEDS if s not in RETAINED_SEEDS]}\n")
        print(f"{'variant':>7} " + " ".join(f"{s:>9}" for s in ALL_SEEDS))
        for v in ALL_VARIANTS:
            cells = []
            for s in ALL_SEEDS:
                d = out_dir_for(v, s)
                cells.append(f"{du(d)/1e6:>6.0f} MB" if os.path.isdir(d) else "        —")
            print(f"{v:>7} " + " ".join(cells))
        on_disk = sum(du(out_dir_for(v, s)) for v in ALL_VARIANTS for s in ALL_SEEDS
                      if os.path.isdir(out_dir_for(v, s)))
        print(f"\non disk: {on_disk/1e9:.2f} GB")
        return 0

    if args.verify:
        if not (args.variant and args.seed):
            sys.exit("--verify needs --variant and --seed")
        have = out_dir_for(args.variant, args.seed)
        if not os.path.isdir(have):
            sys.exit(f"no on-disk copy to compare against: {have}")
        tmp = tempfile.mkdtemp(prefix="regen_")
        try:
            secs, fails, _ = generate(args.variant, args.seed, args.config, tmp)
            names = sorted(f for f in os.listdir(have) if f.endswith(".gz"))
            same = [n for n in names
                    if os.path.exists(os.path.join(tmp, n))
                    and filecmp.cmp(os.path.join(have, n), os.path.join(tmp, n), shallow=False)]
            print(f"determinism: variant {args.variant} seed {args.seed}, "
                  f"{len(same)}/{len(names)} .csv.gz byte-identical to the on-disk copy "
                  f"({secs:.0f}s, {fails} validation failures)")
            for n in names:
                if n not in same:
                    print(f"  DIFFERS: {n}")
            return 0 if len(same) == len(names) else 1
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    if args.all:
        jobs = [(v, s) for v in ALL_VARIANTS for s in ALL_SEEDS if s not in RETAINED_SEEDS]
    elif args.variant and args.seed:
        jobs = [(args.variant, args.seed)]
    else:
        sys.exit("give --variant and --seed, or --all, or --list")

    total = 0.0
    for v, s in jobs:
        d = args.out_dir or out_dir_for(v, s)
        if s in RETAINED_SEEDS and os.path.isdir(d) and not args.out_dir:
            print(f"variant {v} seed {s}: already on disk (retained) — skipping")
            continue
        secs, fails, _ = generate(v, s, args.config, d)
        total += secs
        print(f"variant {v} seed {s}: {secs:6.0f}s  {du(d)/1e6:6.0f} MB  "
              f"{fails} validation failures  -> {d}")
    print(f"\n{len(jobs)} run(s), {total/60:.1f} min total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
